---
  functional:
    - Сайт должен быть совместим с последними версиями браузеров
    - Зарегистрированные пользователи должны иметь возможность установки и иизменения в своём профиле аватара
    - На сайте должна быть реализована функция "начать игру"
    - Необходима реализация нескольких режимов игры "игрок против игрока" / "игрок против компьютера"
    - Во время состязания должен быть реализован чат между игроками
    - В игре должна быть функция проверки правильности решения задачи

  non-functional:
    - Сайт должен быть удобным на мобильном устройстве
    - Сайт должен быть безопасным и защищать данные пользователя
    -  Сайт должен быть способен обрабатывать большое количество трафика
        (например, 1000 одновременных пользователей)
  implicit:
    - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
    - На сайт должны быть добавлены задачи разного уровня сложности
